name: Build
on: [push]
jobs:
  build_latex:
    runs-on: ubuntu-latest
    steps:
      - name: Set up Git repository
        uses: actions/checkout@v2
      - name: Compile document.tex
        uses: dante-ev/latex-action@master
        with:
          root_file: Casadio_Resume_20190905.tex
      - uses: actions/upload-artifact@v2
        with:
          name: resume
          path: Casadio_Resume_20190905.pdf
